/**
 * Cost guards — every automatic path needs a bound. Centralized so each one is
 * testable, and so nobody re-invents a cap inline. Two caps are not one cap:
 * per-analysis caps assume analyses are discrete units (they aren't, under
 * debounced live detection), so the rolling-window cap is the backstop.
 */

export const GUARDS = {
  maxInputChars: 30_000,          // how much text reaches any model call
  maxClaimsPerAnalysis: 40,       // how many claims one detection pass may produce
  maxAutoCritiqueClaims: 6,       // paid fact-checks per analysis, once per analysis id
  maxWebSearchesPerAnalysis: 4,   // paid searches per document analysis
  maxWebSearchesPerHour: 15,      // the backstop when "one analysis" stops meaning anything
  maxAutoSourcesPerCycle: 3,
  evidenceConcurrency: 3,         // claims searched at once in the sweep
  providerTimeoutMs: 6_000,       // a slow index returns empty, not late

  // Live-detect bounds ported from the production app's shared/liveDetect.ts,
  // which solved this already: 2.5s idle (past a comma, short of a reread),
  // a sentence-sized delta (fixing a typo and pausing must not re-read the
  // document), and a 15s floor — the idle timer alone bounds nothing, since
  // type-pause-type clears it forever.
  detect: {
    idleMs: 2500,                 // typing pause before detection may fire
    minChars: 80,                 // minimum draft length
    minDelta: 80,                 // minimum change since last run — sentence-sized
    minIntervalMs: 15_000,        // the hard floor between calls — the real ceiling
  },
};

/**
 * The spend cap's constants.
 *
 * WHY A GLOBAL BUDGET IS THE LOAD-BEARING LAYER, and everything else is
 * politeness:
 *
 * The extension deliberately needs no sign-in, so on a hosted server the
 * DEFAULT caller is anonymous. Anonymous has no identity we control:
 *   - an install id is generated by the client, so it can be rotated freely;
 *   - the client ADDRESS cannot be used for a daily cap at all, because
 *     Tracely's actual market is schools, and a few hundred real students
 *     behind one CGNAT or campus address are indistinguishable from one
 *     attacker behind that same address. A per-address daily quota generous
 *     enough for a school is useless against abuse, and one tight enough for
 *     abuse locks out the school. That option is rejected, not overlooked.
 *
 * So per-caller quotas bound ACCIDENTS and casual overuse, which is most of
 * the real risk, and the global budget is the only thing that bounds a
 * determined attacker. Set DAILY_BUDGET_USD to what you can afford to lose in
 * a day, because that is exactly what it is.
 *
 * Costs on the current fast tier (gpt-5.6-luna, effort medium on /api/check),
 * from the model eval, eval/models/FINDINGS.md, 2026-09-21, measured to cold:
 * a typing-pause check is 0.039-0.104 cents (1 sentence warm to 3 cold;
 * 0.0565-0.086 on an even mix of the two) and a 40-sentence first check
 * 0.34-0.39 cents; a source search is >= 1 cent because OpenAI bills
 * web_search per call ($10/1000) on top of tokens — about 10-25 typing-pause
 * checks. That ratio is why sources are shed first when the budget runs low.
 * (The 2026-09-21 smoke run measured luna source searches at 1.2-1.35 cents,
 * one search each.)
 */
export const SPEND = {
  // Override with TRACELY_DAILY_BUDGET_USD. The default is deliberately small:
  // a pre-revenue launch should find out it was wrong from a 503, not a card
  // statement. $10/day is ~12,000-18,000 typing-pause checks on the fast
  // tier at an even 1-/3-sentence mix (~9,600-25,600 across the full range),
  // or ~29-44 free users at their 400-check cap on that mix (~24 if every
  // check is a cold 3-sentence one; shared/plan.js), or at most ~1,000
  // source searches (the per-call fee alone).
  defaultDailyBudgetUsd: 10,

  // Below this fraction of budget remaining, shed the expensive route first.
  // A source search costs ~10-25x a typing-pause check, so dropping them buys
  // that much runway for the feature people actually notice missing.
  shedSourcesAtRemainingPct: 0.2,

  // Per-caller velocity. The client fires at most 6 checks a minute (one per
  // 10s); 20 leaves room for several tabs and a manual "check now" without
  // ever throttling honest use. Keyed on the CALLER, never on the address.
  callerChecksPerMinute: 20,
  callerSourcesPerMinute: 4,

  // Bounds the rate-limiter map so a rotating-identity attacker cannot grow it
  // without limit. Oldest keys are dropped; a dropped key just gets a fresh
  // allowance, which the daily quota and the global budget still bound.
  rateLimiterMaxKeys: 20_000,

  /* ── the APP pool: the desktop's routes, kept apart from the extension ──
   *
   * The desktop app's AI routes (detect, critique, grade, structure, tracer,
   * correction, find-sources) get their OWN budget, rate limiter and web-search
   * counter. Sharing the extension's would couple the two products: one
   * desktop analysis is roughly 9 model calls plus up to 6 auto-critiques,
   * which alone clears the extension's 20/min caller limit, and desktop Pro
   * traffic on the thorough model would empty the extension's $10 day and
   * 503 every /api/check. Separate pools mean a busy desktop can exhaust
   * only the desktop.
   *
   * Override the budget with TRACELY_APP_DAILY_BUDGET_USD (same rules as the
   * extension's: empty is "absent", junk is the default, explicit 0 is off).
   * It must SCALE WITH SUBSCRIBERS, like the paid pool below: set it to
   * max(10, 0.15 x paying subscribers). */
  defaultAppDailyBudgetUsd: 10,
  appCallerCallsPerMinute: 30,
  appCallerSearchesPerHour: 25,

  /* ── the BETA pool: testers on the unpacked beta build, granted Pro ──
   *
   * A caller presenting a valid X-Tracely-Beta token (TRACELY_BETA_TOKENS) is
   * served as Pro on the extension's routes, and that spend lands HERE, never
   * in the extension pool. When this pool runs out the caller silently drops
   * back to its own plan on the extension pool — so beta usage can neither
   * 503 anyone nor eat the day paying and free extension users run on.
   *
   * Override with TRACELY_BETA_DAILY_BUDGET_USD, same rules as the others:
   * empty is "absent", junk is the default, and an explicit 0 turns the
   * CEILING off (unlimited beta spend) — it does not turn beta off. Emptying
   * TRACELY_BETA_TOKENS is what turns beta off. */
  defaultBetaDailyBudgetUsd: 10,
  /* Beta source searches get their own process-wide hourly window. A tester is
   * Pro, so no daily source quota applies; on the extension's shared 15/hour
   * counter one tester with auto-sources on could take the whole hour and 429
   * every store user's source search. Theirs is paid by the beta pool, so it
   * is bounded by the pool — this only keeps the two sets of users apart. */
  betaWebSearchesPerHour: 30,

  /* ── the PAID pool: Student and Pro accounts on the extension's routes ──
   *
   * Hosted /api/check, /api/flow and /api/sources run the fast model on every
   * plan since the 2026-09-21 plan policy, except Pro's "Explain in depth" on
   * the thorough model (~40-50x the fast one per token) out of a monthly
   * allowance. Paid traffic must still never spend the free users' day — the
   * exact failure the app pool exists to prevent — so paid-plan calls on the
   * extension routes spend HERE; when this pool is spent they drop to the fast
   * model on the extension pool (their plan, and so their quotas, unchanged).
   *
   * It must SCALE WITH SUBSCRIBERS: a regular Pro user spends ~9 cents a day
   * and a regular Student ~4 (their per-account fair-use limits are $2 and $1
   * a day), so at $10 this pool binds at roughly 110-240 active regular users
   * a day. Set TRACELY_PAID_DAILY_BUDGET_USD (and TRACELY_APP_DAILY_BUDGET_USD)
   * to max(10, 0.15 x paying subscribers).
   *
   * Override with TRACELY_PAID_DAILY_BUDGET_USD, same rules as the others. */
  defaultPaidDailyBudgetUsd: 10,
};

/**
 * Dollars of daily budget, from the environment.
 *
 * An EMPTY value is "absent", not "0". Number("") is 0, and 0 means unlimited
 * here — so the obvious `TRACELY_DAILY_BUDGET_USD=` line in an .env.example
 * would have silently removed the ceiling. Only an explicit numeric 0 does
 * that, which is the documented way to turn it off.
 */
export function dailyBudgetUsd(env = process.env, variable = "TRACELY_DAILY_BUDGET_USD", fallback = SPEND.defaultDailyBudgetUsd) {
  const text = String(env[variable] ?? "").trim();
  if (!text) return fallback;
  const raw = Number(text);
  if (!Number.isFinite(raw) || raw < 0) return fallback;
  return raw;
}

/**
 * Rolling-window counter. stamp() BEFORE the call, not after — otherwise it
 * measures the gap between answers instead of between requests.
 */
export function rollingCounter(limit, windowMs = 3_600_000) {
  let times = [];
  return {
    ok() {
      const now = Date.now();
      times = times.filter((t) => now - t < windowMs);
      return times.length < limit;
    },
    stamp() {
      times.push(Date.now());
    },
    count() {
      const now = Date.now();
      times = times.filter((t) => now - t < windowMs);
      return times.length;
    },
  };
}

/**
 * Debounce-floor gate for live detection. The idle timer bounds nothing on its
 * own (type-pause-type clears it forever); the floor between calls is the
 * actual ceiling, stamped before the call.
 */
export function detectGate() {
  /* The desktop's rule (src/shared/liveDetect.ts shouldDetectNow), mirrored and
   * pinned by test/mirror-contracts.test.js. Two ways this copy used to differ:
   *  - it measured the RAW draft, so 79 characters and a few trailing spaces
   *    cleared the 80-character minimum here and not on the desktop;
   *  - it started from lastRunAt = 0, so "has never run" was only distinguished
   *    from "ran at the epoch" by the real clock being large. Null says it.
   * Both measure the trimmed draft now, and a first run skips the floor. */
  let lastRunAt = null;
  let lastText = null;
  return {
    shouldRun(raw, now = Date.now()) {
      const text = String(raw ?? "").trim();
      if (text.length < GUARDS.detect.minChars) return false;
      if (lastText !== null) {
        if (text === lastText) return false;
        if (Math.abs(text.length - lastText.length) < GUARDS.detect.minDelta) return false;
      }
      if (lastRunAt !== null && now - lastRunAt < GUARDS.detect.minIntervalMs) return false;
      return true;
    },
    stamp(raw, now = Date.now()) {
      lastRunAt = now; // before the call
      lastText = String(raw ?? "").trim();
    },
  };
}

/**
 * Per-key rolling rate limiter — one rollingCounter per caller, bounded.
 *
 * In memory on purpose: this bounds BURSTS, and a burst does not survive a
 * restart. The daily quotas are in SQLite because those must survive one.
 *
 * Eviction is oldest-first on insertion order rather than true LRU. A busy
 * caller can therefore be evicted and get a fresh allowance; that is
 * acceptable because this layer only smooths velocity — the daily quota and
 * the global budget are what actually bound spend.
 */
export function keyedRateLimiter(limit, windowMs = 60_000, maxKeys = SPEND.rateLimiterMaxKeys) {
  const byKey = new Map();
  return {
    ok(key) {
      const c = byKey.get(key);
      return c ? c.ok() : true;
    },
    stamp(key) {
      let c = byKey.get(key);
      if (!c) {
        if (byKey.size >= maxKeys) {
          for (const k of byKey.keys()) {
            byKey.delete(k);
            if (byKey.size < maxKeys) break;
          }
        }
        c = rollingCounter(limit, windowMs);
        byKey.set(key, c);
      }
      c.stamp();
    },
    size() {
      return byKey.size;
    },
  };
}
